exec sp_pop_assembly_UK 3
exec sp_pop_serialnum_UK 3
exec sp_pop_Manufacturing_ID_UK 3
exec sp_pop_SKU_UK 3
exec sp_pop_Regulatory_Model_UK 3
exec sp_pop_Partnum_UK 3
exec sp_Location_UK 3
exec sp_Stepresult_code_UK 3
exec sp_pop_Firmware_UK 3
exec sp_pop_ROMV_UK 3
exec sp_pop_safemodever_UK 3
exec sp_pop_Station_UK 3
exec sp_pop_Stationtype_UK 3
exec sp_pop_datecode_UK 3