use MFTG_DW
-- MFGTESTC_TAIWAN
exec sp_pop_assembly_taiwan_label 8
exec sp_pop_serialnumber_taiwan_label 8
exec sp_pop_manufacturing_id_taiwan_label 8
exec sp_pop_firmversion_taiwan_label 8
exec sp_pop_romversion_taiwan_label 8
exec sp_pop_safemodeversion_taiwan_label 8
exec sp_pop_IRV_taiwan_label 8
exec sp_pop_regulatorymodel_taiwan_label 8
exec sp_pop_station_taiwan_label 8 
exec sp_pop_Location_taiwan_label 8
exec sp_pop_SKU_taiwan_label 8
exec sp_pop_Partnum_taiwan_label 8
exec sp_pop_Stepresult_code_taiwan_label 8
exec sp_pop_Stationtype_taiwan_label 8
      
