--MFGTESTC_FREMONT
exec sp_pop_assembly_FREMONT 2
exec sp_pop_serialnum_FREMONT 2
exec sp_pop_Manufacturing_ID_FREMONT 2
exec sp_pop_SKU_FREMONT 2
exec sp_pop_Regulatory_Model_FREMONT 2
exec sp_pop_Partnum_FREMONT 2
exec sp_Location_FREMONT 2
exec sp_Stepresult_code_FREMONT 2
exec sp_pop_Firmware_FREMONT 2
exec sp_pop_ROMV_FREMONT 2
exec sp_pop_safemodever_FREMONT 2
exec sp_pop_Station_FREMONT 2
exec sp_pop_Stationtype_FREMONT 2
exec sp_pop_datecode_FREMONT 2